# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # runs during prebuild
  - init: |
      echo 'do nothing' 
    command: npm i -g simple-server
  - init: |
      echo 'hello' 
    command: >
      cd /workspace/coape
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
